# Generated by Django 5.0.3 on 2024-04-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.FloatField(default=0.5),
        ),
    ]
